### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by artstylee** [ItsJustMeChris/Classic-WoW-Fishbot#1]
doesnt work.
nothing happens 
the last 2 lines in the terminal is f7 toggle pause and f8 close
pressing f7 gives bot state 1
pressing f8 gives quit
??? am i doing smt wrong?

**Comment by ItsJustMeChris** [comment]
The offsets are not updated to the newest version of the game. 

You'd need to find and update these two offsets.
auto pCameraBase = m.read<uintptr_t>(m.m_base + 0x2535398); 
auto pObjMgr = m.read<uintptr_t>(m.m_base + 0x231CED8);

**Comment by artstylee** [comment]
well iam not  a proger actually
can u suggest how do i do it
